$ErrorActionPreference='Stop'
$Root=Split-Path -Parent $PSScriptRoot
$html=Get-Content (Join-Path $Root 'src\index.template.html') -Raw -Encoding UTF8
$required=@('InferenceSession','face_detection_yunet_2026may.onnx','face_recognition_sface_2021dec_int8.onnx','sface-2021dec-int8-ort','tensorFromCanvas','paddedCanvas32','yunetOutputs','Math.sqrt(clsScore*objScore)','alignFaceCanvas','SFACE_TEMPLATE','indexedDB','Float32Array','getUserMedia','cameraVideo','checkedInAt','CAMERA_CONFIRM_HITS=2','view-history','historyList','historyCount','checkedInScore','exportCsvBtn','exportJsonBtn','biometricDataIncluded','thresholdRange','marginRange','MATCH_PRESETS','EMBEDDING_MODEL','embeddingModel','compatiblePeople','modelNotice','receptionModeBtn','receptionBar','recentCheckins','cameraGuide','registerBatchSummary','registrationFailureDialog','sessionDialog','privacyAck','SESSION_META_KEY','TEMP_META_KEY','MAX_EMBEDDINGS=3','embeddingsOf','addEmbeddingToPerson','sessionStorage','deleteAllDialog','deleteEmbeddingCount','sessionChangeBtn','sessionCloseBtn','changeRetentionMode','replacePersistentSnapshot','replaceTempSnapshot','Pop-up Face Check-in','その場で使って、終わったら消す。','data-ja="受付"','data-ja="照合結果"','data-manual-checkin','manualCheckin','checkedInMethod','手動で受付','resetCheckinDialog','confirmResetCheckin','deletePersonDialog','openDeletePersonDialog','confirmDeletePerson','peopleCsvBtn','registrationExportBtn','registrationImportBtn','registrationExportDialog','registrationImportDialog','REGISTRATION_FILE_TYPE','REGISTRATION_FILE_VERSION','encryptRegistrationPayload','decryptRegistrationEnvelope','PBKDF2','AES-GCM','.popupface','registrationImportAck','password-toggle','bindPasswordToggles','i-eye','i-eye-off','i-file-lock','ui-icon','workflowMode','entryexit','checkEvents','peopleSearch','data-people-filter','duplicateDialog','duplicateCandidateFor','removeEmbeddingDialog','manualReceptionDialog','preflightDialog','entryExitBlockedId','advanced-settings','result-diagnostics','app-mobile-bottom-bar','app-mobile-bottom-item','has-mobile-bottom-bar','app-footer','prefers-reduced-motion')
foreach($s in $required){if(-not$html.Contains($s)){throw "Required content missing: $s"}}
if($html -match 'prefers-color-scheme'){throw 'Dark mode must not be enabled.'}
if($html -match 'FaceDetectorYN|FaceRecognizerSF|cvApi|opencv\.js'){throw 'OpenCV dependency must not remain in the runtime HTML.'}
if($html -match '顔認証|顔認識|生体認証|本人候補'){throw 'Authentication/recognition-oriented Japanese wording must not remain in the user-facing HTML.'}
if($html -match '\bconfirm\('){throw 'Native confirm dialogs must not be used; use app-styled dialogs.'}
Write-Host 'Repository checks passed.'

$templateFiles=@('APP_SPEC.md','app.config.json','dependencies.json','README.ja.md','SECURITY.md','VERIFY_OFFLINE.md','schemas\app-config.schema.json','schemas\dependencies.schema.json','components\mobile-bottom-bar.html')
foreach($f in $templateFiles){if(-not(Test-Path(Join-Path $Root $f))){throw "Template-aligned repository file missing: $f"}}
if(-not (Get-Content (Join-Path $Root 'README.md') -Raw -Encoding UTF8).Contains('assets/screenshot.png')){throw 'README must reference assets/screenshot.png.'}
Write-Host 'htmlapps-template alignment checks passed.'
